/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author kaiqu
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        //Aba selecionada cor
        UIManager.put("TabbedPane.selected", Color.DARK_GRAY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        tVendas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pesquisarCustom2 = new JCustoms.PesquisarCustom();
        tProdutos = new javax.swing.JPanel();
        tClientes = new javax.swing.JPanel();
        tRelatorios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(134, 83, 83));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTabbedPane2.setOpaque(true);
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        tVendas.setBackground(new java.awt.Color(255, 255, 255));
        tVendas.setForeground(new java.awt.Color(255, 51, 51));
        tVendas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tVendasFocusGained(evt);
            }
        });
        tVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tVendasMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");

        pesquisarCustom2.setForeground(new java.awt.Color(0, 0, 0));
        pesquisarCustom2.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        javax.swing.GroupLayout tVendasLayout = new javax.swing.GroupLayout(tVendas);
        tVendas.setLayout(tVendasLayout);
        tVendasLayout.setHorizontalGroup(
            tVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tVendasLayout.createSequentialGroup()
                .addGroup(tVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tVendasLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButton1))
                    .addGroup(tVendasLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(pesquisarCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        tVendasLayout.setVerticalGroup(
            tVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tVendasLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(pesquisarCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("    Vendas    ", tVendas);

        tProdutos.setForeground(new java.awt.Color(102, 0, 255));
        tProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProdutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tProdutosLayout = new javax.swing.GroupLayout(tProdutos);
        tProdutos.setLayout(tProdutosLayout);
        tProdutosLayout.setHorizontalGroup(
            tProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tProdutosLayout.setVerticalGroup(
            tProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Produtos", tProdutos);

        tClientes.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout tClientesLayout = new javax.swing.GroupLayout(tClientes);
        tClientes.setLayout(tClientesLayout);
        tClientesLayout.setHorizontalGroup(
            tClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tClientesLayout.setVerticalGroup(
            tClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Clientes", tClientes);

        tRelatorios.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout tRelatoriosLayout = new javax.swing.GroupLayout(tRelatorios);
        tRelatorios.setLayout(tRelatoriosLayout);
        tRelatoriosLayout.setHorizontalGroup(
            tRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tRelatoriosLayout.setVerticalGroup(
            tRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Relátorios", tRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProdutosMouseClicked
        //tProdutos.setBackground(Color.yellow);
    }//GEN-LAST:event_tProdutosMouseClicked

    private void tVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tVendasMouseClicked
       
    }//GEN-LAST:event_tVendasMouseClicked

    private void tVendasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tVendasFocusGained
        
    }//GEN-LAST:event_tVendasFocusGained

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
      
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowss".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private JCustoms.PesquisarCustom pesquisarCustom2;
    private javax.swing.JPanel tClientes;
    private javax.swing.JPanel tProdutos;
    private javax.swing.JPanel tRelatorios;
    private javax.swing.JPanel tVendas;
    // End of variables declaration//GEN-END:variables
}
